export const dashboardRows = [
  {
    id: 1000,
    name: "James Butt",
    country: {
      name: "Algeria",
      code: "dz",
    },
    company: "Benton, John B Jr",
    date: "2015-09-13",
    status: "unqualified",
    verified: true,
    activity: 17,
    representative: {
      name: "Farhan",
      image: "ionibowcher.png",
    },
    balance: 70663,
  },
  {
    id: 1000,
    name: "James Butt",
    country: {
      name: "Algeria",
      code: "dz",
    },
    company: "Benton, John B Jr",
    date: "2015-09-13",
    status: "unqualified",
    verified: true,
    activity: 17,
    representative: {
      name: "Ioni Bowcher",
      image: "ionibowcher.png",
    },
    balance: 70663,
  },
  {
    id: 1000,
    name: "James Butt",
    country: {
      name: "Algeria",
      code: "dz",
    },
    company: "Benton, John B Jr",
    date: "2015-09-13",
    status: "unqualified",
    verified: true,
    activity: 17,
    representative: {
      name: "Ioni Bowcher",
      image: "ionibowcher.png",
    },
    balance: 70663,
  },
  {
    id: 1000,
    name: "James Butt",
    country: {
      name: "Algeria",
      code: "dz",
    },
    company: "Benton, John B Jr",
    date: "2015-09-13",
    status: "unqualified",
    verified: true,
    activity: 17,
    representative: {
      name: "Ioni Bowcher",
      image: "ionibowcher.png",
    },
    balance: 70663,
  },
  {
    id: 1000,
    name: "James Butt",
    country: {
      name: "Algeria",
      code: "dz",
    },
    company: "Benton, John B Jr",
    date: "2015-09-13",
    status: "unqualified",
    verified: true,
    activity: 17,
    representative: {
      name: "Ioni Bowcher",
      image: "ionibowcher.png",
    },
    balance: 70663,
  },
  {
    id: 1000,
    name: "James Butt",
    country: {
      name: "Algeria",
      code: "dz",
    },
    company: "Benton, John B Jr",
    date: "2015-09-13",
    status: "unqualified",
    verified: true,
    activity: 17,
    representative: {
      name: "Ioni Bowcher",
      image: "ionibowcher.png",
    },
    balance: 70663,
  },
  {
    id: 1000,
    name: "James Butt",
    country: {
      name: "Algeria",
      code: "dz",
    },
    company: "Benton, John B Jr",
    date: "2015-09-13",
    status: "unqualified",
    verified: true,
    activity: 17,
    representative: {
      name: "Ioni Bowcher",
      image: "ionibowcher.png",
    },
    balance: 70663,
  },
  {
    id: 1000,
    name: "James Butt",
    country: {
      name: "Algeria",
      code: "dz",
    },
    company: "Benton, John B Jr",
    date: "2015-09-13",
    status: "unqualified",
    verified: true,
    activity: 17,
    representative: {
      name: "Ioni Bowcher",
      image: "ionibowcher.png",
    },
    balance: 70663,
  },
  {
    id: 1000,
    name: "James Butt",
    country: {
      name: "Algeria",
      code: "dz",
    },
    company: "Benton, John B Jr",
    date: "2015-09-13",
    status: "unqualified",
    verified: true,
    activity: 17,
    representative: {
      name: "Ioni Bowcher",
      image: "ionibowcher.png",
    },
    balance: 70663,
  },
  {
    id: 1000,
    name: "James Butt",
    country: {
      name: "Algeria",
      code: "dz",
    },
    company: "Benton, John B Jr",
    date: "2015-09-13",
    status: "unqualified",
    verified: true,
    activity: 17,
    representative: {
      name: "Ioni Bowcher",
      image: "ionibowcher.png",
    },
    balance: 70663,
  },
  {
    id: 1000,
    name: "James Butt",
    country: {
      name: "Algeria",
      code: "dz",
    },
    company: "Benton, John B Jr",
    date: "2015-09-13",
    status: "unqualified",
    verified: true,
    activity: 17,
    representative: {
      name: "Ioni Bowcher",
      image: "ionibowcher.png",
    },
    balance: 70663,
  },
  {
    id: 1000,
    name: "James Butt",
    country: {
      name: "Algeria",
      code: "dz",
    },
    company: "Benton, John B Jr",
    date: "2015-09-13",
    status: "unqualified",
    verified: true,
    activity: 17,
    representative: {
      name: "Ioni Bowcher",
      image: "ionibowcher.png",
    },
    balance: 70663,
  },
];

export const pendingEnrollmentsRows = [
  {
    id: 10002,
    date: "July 22, 2024",
    name: "Thomas Blackwood",
    dob: "10/16/1951",
    practice: "East Valley Family Physicians",
    deviceType: "BP",
    programType: ["RPM, CCM"],
    status: "First Call",
    progress: 75,
    consent: "Yes",
  },
  {
    id: 10003,
    date: "July 22, 2024",
    name: "James Huddleson",
    dob: "06/23/1980",
    practice: "East Valley Family Physicians",
    deviceType: "BP",
    programType: ["RPM, CCM"],
    status: "Second Call",
    progress: 45,
    consent: "Yes",
  },
  {
    id: 10004,
    date: "July 22, 2024",
    name: "Jim Carter",
    dob: "02/26/1980",
    practice: "East Valley Family Physicians",
    deviceType: "BP",
    programType: ["RPM, CCM"],
    status: "First Call",
    progress: 25,
    consent: "Yes",
  },
  {
    id: 10005,
    date: "July 22, 2024",
    name: "Chris Hemsworth",
    dob: "12/03/1987",
    practice: "East Valley Family Physicians",
    deviceType: "BP",
    programType: ["RPM, CCM"],
    status: "First Call",
    progress: 100,
    consent: "No",
  },
];
export const pendingReadingsRows = [
  {
    id: 7158,
    image: "https://randomuser.me/api/portraits/women/75.jpg",
    dob: "NOV 24, 1950",
    name: "Diana Case",
    type: ["RPM", "CCM"],
    medicare: "Medicare",
    practice: "IntraCare Health Center - Fort Worth",
    provider: "Dr Smith",
    date: "Jul 23 2024",
    trackingStatus: "NO_TRACKING",
    shipped: true,
    trackingDescription: "Non Tracking",
    stageClass: "text-red-500",
    statusClass: "bg-green-100 text-green-700",
  },
  {
    id: 7040,
    image: "https://randomuser.me/api/portraits/men/75.jpg",
    dob: "JAN 12, 1984",
    name: "Gabrielle Hanes",
    type: ["RPM", "CCM"],
    medicare: "Medicare",
    practice: "Prime MD Geriatrics",
    provider: "Dr Kevin",
    date: "Dec 23 2023",
    trackingStatus: "TRACKING",
    shipped: false,
    trackingDescription: "Tracking",
    stageClass: "text-red-500",
    statusClass: "bg-green-100 text-green-700",
  },
  {
    id: 7451,
    image: "https://randomuser.me/api/portraits/women/52.jpg",
    dob: "MAY 14, 1975",
    name: "Samantha Walters",
    type: ["CCM"],
    medicare: "Medicare",
    practice: "Downtown Family Care",
    provider: "Dr Williams",
    date: "Sep 15 2023",
    trackingStatus: "TRACKING",
    shipped: true,
    trackingDescription: "Tracking",
    stageClass: "text-blue-500",
    statusClass: "bg-yellow-100 text-yellow-700",
  },
  {
    id: 7530,
    image: "https://randomuser.me/api/portraits/men/65.jpg",
    dob: "OCT 01, 1962",
    name: "Michael Harper",
    type: ["RPM"],
    medicare: "Medicare Advantage",
    practice: "Parkway Healthcare",
    provider: "Dr Allen",
    date: "Aug 17 2024",
    trackingStatus: "NO_TRACKING",
    shipped: false,
    trackingDescription: "Non Tracking",
    stageClass: "text-red-500",
    statusClass: "bg-green-100 text-green-700",
  },
  {
    id: 7673,
    image: "https://randomuser.me/api/portraits/women/31.jpg",
    dob: "FEB 28, 1992",
    name: "Jessica Green",
    type: ["RPM", "CCM"],
    medicare: "Medicare",
    practice: "Cedar Park Health Clinic",
    provider: "Dr Garcia",
    date: "Jul 5 2024",
    trackingStatus: "TRACKING",
    shipped: true,
    trackingDescription: "Tracking",
    stageClass: "text-blue-500",
    statusClass: "bg-blue-100 text-blue-700",
  },
  {
    id: 7123,
    image: "https://randomuser.me/api/portraits/men/15.jpg",
    dob: "MAR 11, 1955",
    name: "Brian Jennings",
    type: ["CCM"],
    medicare: "Medicare",
    practice: "Oak Ridge Medical Center",
    provider: "Dr Johnson",
    date: "Jun 21 2024",
    trackingStatus: "NO_TRACKING",
    shipped: false,
    trackingDescription: "Non Tracking",
    stageClass: "text-red-500",
    statusClass: "bg-red-100 text-red-700",
  },
  {
    id: 7891,
    image: "https://randomuser.me/api/portraits/women/20.jpg",
    dob: "APR 18, 1980",
    name: "Nancy Stephens",
    type: ["RPM"],
    medicare: "Medicare Advantage",
    practice: "Sunshine Health Partners",
    provider: "Dr Adams",
    date: "Oct 9 2023",
    trackingStatus: "TRACKING",
    shipped: true,
    trackingDescription: "Tracking",
    stageClass: "text-blue-500",
    statusClass: "bg-green-100 text-green-700",
  },
  {
    id: 7325,
    image: "https://randomuser.me/api/portraits/men/24.jpg",
    dob: "JUL 22, 1978",
    name: "James Washington",
    type: ["RPM", "CCM"],
    medicare: "Medicare",
    practice: "Pine Grove Medical",
    provider: "Dr Thompson",
    date: "Sep 29 2024",
    trackingStatus: "NO_TRACKING",
    shipped: false,
    trackingDescription: "Non Tracking",
  },
  {
    id: 7152,
    image: "https://randomuser.me/api/portraits/women/34.jpg",
    dob: "DEC 10, 1966",
    name: "Ashley Turner",
    type: ["CCM"],
    medicare: "Medicare Advantage",
    practice: "Northwest Health Group",
    provider: "Dr Parker",
    date: "Nov 30 2023",
    trackingStatus: "TRACKING",
    shipped: true,
    trackingDescription: "Tracking",
    stageClass: "text-blue-500",
    statusClass: "bg-green-100 text-green-700",
  },
  {
    id: 7982,
    image: "https://randomuser.me/api/portraits/men/45.jpg",
    dob: "AUG 5, 1970",
    name: "David Carter",
    type: ["RPM", "CCM"],
    medicare: "Medicare",
    practice: "Southwest Medical Group",
    provider: "Dr Anderson",
    date: "May 13 2024",
    trackingStatus: "NO_TRACKING",
    shipped: false,
    trackingDescription: "Non Tracking",
  },
];
export const readingNotAddressedRows = [
  {
    id: 7158,
    image: "https://randomuser.me/api/portraits/women/75.jpg",
    name: "Diana Case",
    practice: "IntraCare Health Center - Fort Worth",
    date: "Jul 23 2024",
    readingType: "Blood Pressure",
    reading: "147/81",
    stage: "Hypertension Stage 2",
    stageClass: "text-red-500",
    source: "Tupelolife",
    status: true,
  },
  {
    id: 7040,
    image: "https://randomuser.me/api/portraits/men/75.jpg",
    name: "Gabrielle Hanes",
    practice: "Prime MD Geriatrics",
    date: "Jul 23 2024",
    readingType: "Blood Pressure",
    reading: "153/93",
    stage: "Hypertension Stage 2",
    stageClass: "text-red-500",
    source: "Tupelolife",
    status: false,
  },
  {
    id: 9083,
    image: "https://randomuser.me/api/portraits/women/10.jpg",
    name: "Marta Griffin",
    practice: "Parkway Medical Center",
    date: "Jun 15 2024",
    readingType: "Heart Rate",
    reading: "88 bpm",
    stage: "Normal",
    stageClass: "text-green-500",
    source: "Fitbit",
    status: true,
  },
  {
    id: 3457,
    image: "https://randomuser.me/api/portraits/men/20.jpg",
    name: "John Doe",
    practice: "Eastside Health Clinic",
    date: "Sep 5 2024",
    readingType: "Blood Sugar",
    reading: "125 mg/dL",
    stage: "Pre-diabetes",
    stageClass: "text-yellow-500",
    source: "Glucolife",
    status: false,
  },
  {
    id: 5674,
    image: "https://randomuser.me/api/portraits/women/30.jpg",
    name: "Emily Foster",
    practice: "Central Wellness Clinic",
    date: "Aug 12 2024",
    readingType: "Cholesterol",
    reading: "220 mg/dL",
    stage: "Borderline High",
    stageClass: "text-orange-500",
    source: "LabCorp",
    status: true,
  },
  {
    id: 1823,
    image: "https://randomuser.me/api/portraits/men/40.jpg",
    name: "James Taylor",
    practice: "Bay Area Health Center",
    date: "Oct 1 2024",
    readingType: "Blood Pressure",
    reading: "130/85",
    stage: "Pre-hypertension",
    stageClass: "text-yellow-500",
    source: "Omron",
    status: false,
  },
  {
    id: 6245,
    image: "https://randomuser.me/api/portraits/women/50.jpg",
    name: "Sandra Mitchell",
    practice: "Sunrise Family Health",
    date: "May 30 2024",
    readingType: "Heart Rate",
    reading: "102 bpm",
    stage: "Elevated",
    stageClass: "text-red-500",
    source: "Apple Watch",
    status: true,
  },
  {
    id: 8792,
    image: "https://randomuser.me/api/portraits/men/60.jpg",
    name: "Aaron Black",
    practice: "Greenwood Medical Center",
    date: "Apr 20 2024",
    readingType: "Blood Sugar",
    reading: "95 mg/dL",
    stage: "Normal",
    stageClass: "text-green-500",
    source: "Dexcom",
    status: true,
  },
  {
    id: 9321,
    image: "https://randomuser.me/api/portraits/women/70.jpg",
    name: "Jessica Brown",
    practice: "Westside Health Clinic",
    date: "Mar 18 2024",
    readingType: "Cholesterol",
    reading: "190 mg/dL",
    stage: "Desirable",
    stageClass: "text-green-500",
    source: "LabCorp",
    status: false,
  },
  {
    id: 4519,
    image: "https://randomuser.me/api/portraits/men/80.jpg",
    name: "Michael Harris",
    practice: "Downtown Medical Center",
    date: "Jan 10 2024",
    readingType: "Blood Pressure",
    reading: "160/100",
    stage: "Hypertension Stage 2",
    stageClass: "text-red-500",
    source: "Withings",
    status: false,
  },
];

export const mockDevicesData = [
  {
    type: "Blood Pressure Monitor",
    issueDate: "20-12-2222",
    serial: "124qiyeu49792",
    active: true,
  },
  {
    type: "Blood Pressure Monitor",
    issueDate: "20-12-2222",
    serial: "124qiyeu49792",
    active: false,
  },
  {
    type: "Blood Pressure Monitor",
    issueDate: "20-12-2222",
    serial: "124qiyeu49792",
    active: true,
  },
  {
    type: "Blood Pressure Monitor",
    issueDate: "20-12-2222",
    serial: "124qiyeu49792",
    active: true,
  },
  {
    type: "Blood Pressure Monitor",
    issueDate: "20-12-2222",
    serial: "124qiyeu49792",
    active: false,
  },
  {
    type: "Blood Pressure Monitor",
    issueDate: "20-12-2222",
    serial: "124qiyeu49792",
    active: false,
  },
];
export const callLogsData = [
  {
    dateTime: "Sep 30, 2024",
    callFrom: "Patient A",
    callTo: "Provider A",
    phoneNumber: "1234567890",
    startTime: "10:00 AM",
    endTime: "10:30 AM",
    duration: "00:30",
    status: "Completed",
  },
  {
    dateTime: "Oct 01, 2024",
    callFrom: "Patient B",
    callTo: "Dr. Smith",
    phoneNumber: "9876543210",
    startTime: "09:45 AM",
    endTime: "10:00 AM",
    duration: "00:15",
    status: "Missed",
  },
  {
    dateTime: "Oct 02, 2024",
    callFrom: "Patient C",
    callTo: "Dr. Allen",
    phoneNumber: "5554443333",
    startTime: "01:00 PM",
    endTime: "01:20 PM",
    duration: "00:20",
    status: "Completed",
  },
  {
    dateTime: "Oct 03, 2024",
    callFrom: "Patient D",
    callTo: "Provider B",
    phoneNumber: "3332221111",
    startTime: "11:30 AM",
    endTime: "11:50 AM",
    duration: "00:20",
    status: "Completed",
  },
  {
    dateTime: "Oct 04, 2024",
    callFrom: "Patient E",
    callTo: "Dr. Wilson",
    phoneNumber: "4445556666",
    startTime: "02:00 PM",
    endTime: "02:45 PM",
    duration: "00:45",
    status: "Completed",
  },
  {
    dateTime: "Sep 30, 2024",
    callFrom: "Patient A",
    callTo: "Provider A",
    phoneNumber: "1234567890",
    startTime: "10:00 AM",
    endTime: "10:30 AM",
    duration: "00:30",
    status: "Completed",
  },
  {
    dateTime: "Oct 01, 2024",
    callFrom: "Patient B",
    callTo: "Dr. Smith",
    phoneNumber: "9876543210",
    startTime: "09:45 AM",
    endTime: "10:00 AM",
    duration: "00:15",
    status: "Missed",
  },
  {
    dateTime: "Oct 02, 2024",
    callFrom: "Patient C",
    callTo: "Dr. Allen",
    phoneNumber: "5554443333",
    startTime: "01:00 PM",
    endTime: "01:20 PM",
    duration: "00:20",
    status: "Completed",
  },
  {
    dateTime: "Oct 03, 2024",
    callFrom: "Patient D",
    callTo: "Provider B",
    phoneNumber: "3332221111",
    startTime: "11:30 AM",
    endTime: "11:50 AM",
    duration: "00:20",
    status: "Completed",
  },
  {
    dateTime: "Oct 04, 2024",
    callFrom: "Patient E",
    callTo: "Dr. Wilson",
    phoneNumber: "4445556666",
    startTime: "02:00 PM",
    endTime: "02:45 PM",
    duration: "00:45",
    status: "Completed",
  },
];

export const textLogsData = [
  {
    dateTime: "Sep 30, 2024",
    phoneNumber: "1234567890",
    message: "Reminder: Blood Pressure Check",
    readingType: "Blood Pressure",
    messageStatus: "Sent",
    patientName: "Patient A",
    providerName: "Dr. John",
  },
  {
    dateTime: "Oct 01, 2024",
    phoneNumber: "9876543210",
    message: "Medication Reminder",
    readingType: "Heart Rate",
    messageStatus: "Delivered",
    patientName: "Patient B",
    providerName: "Dr. Smith",
  },
  {
    dateTime: "Oct 02, 2024",
    phoneNumber: "5554443333",
    message: "Appointment Reminder",
    readingType: "Cholesterol",
    messageStatus: "Sent",
    patientName: "Patient C",
    providerName: "Dr. Allen",
  },
  {
    dateTime: "Oct 03, 2024",
    phoneNumber: "3332221111",
    message: "Weekly Health Update",
    readingType: "Blood Sugar",
    messageStatus: "Failed",
    patientName: "Patient D",
    providerName: "Dr. Clark",
  },
  {
    dateTime: "Oct 04, 2024",
    phoneNumber: "4445556666",
    message: "Follow-up Reminder",
    readingType: "Weight",
    messageStatus: "Delivered",
    patientName: "Patient E",
    providerName: "Dr. Wilson",
  },
];
export const timerLogsData = [
  {
    dateTime: "Sep 30, 2024",
    takenBy: "Ajmal Shami",
    startTime: "10:00AM",
    endTime: "10:30AM",
    duration: "00:30",
    billable: "Yes",
    billingCategory: "RPM",
    logType: "Timer",
    patientName: "Patient A",
    doctorName: "Dr. John",
  },
  {
    dateTime: "Oct 01, 2024",
    takenBy: "Training Provider 1",
    startTime: "08:00AM",
    endTime: "08:30AM",
    duration: "00:30",
    billable: "No",
    billingCategory: "CCM",
    logType: "Timer",
    patientName: "Patient B",
    doctorName: "Dr. Smith",
  },
  {
    dateTime: "Oct 02, 2024",
    takenBy: "Training Provider 2",
    startTime: "09:00AM",
    endTime: "09:45AM",
    duration: "00:45",
    billable: "Yes",
    billingCategory: "RPM",
    logType: "Timer",
    patientName: "Patient C",
    doctorName: "Dr. Allen",
  },
  {
    dateTime: "Oct 03, 2024",
    takenBy: "Training Provider 3",
    startTime: "10:15AM",
    endTime: "10:45AM",
    duration: "00:30",
    billable: "No",
    billingCategory: "CCM",
    logType: "Timer",
    patientName: "Patient D",
    doctorName: "Dr. Clark",
  },
  {
    dateTime: "Oct 04, 2024",
    takenBy: "Training Provider 4",
    startTime: "11:00AM",
    endTime: "11:30AM",
    duration: "00:30",
    billable: "Yes",
    billingCategory: "RPM",
    logType: "Timer",
    patientName: "Patient E",
    doctorName: "Dr. Wilson",
  },
];
export const biometricsMockData = [
  {
    metricName: "Blood Glucose",
    value: "98",
    metricUnit: "mg/dL",
    date: "Oct 5, 2024 at 8:15:00 AM",
  },
  {
    metricName: "Blood Pressure",
    value: "120/80",
    metricUnit: "mmHg",
    date: "Oct 3, 2024 at 7:45:00 AM",
  },
  {
    metricName: "Weight",
    value: "165",
    metricUnit: "lbs",
    date: "Sep 29, 2024 at 9:30:00 AM",
  },
  {
    metricName: "Oxygen Saturation",
    value: "98",
    metricUnit: "%",
    date: "Oct 4, 2024 at 5:10:00 PM",
  },
  {
    metricName: "Heart Rate",
    value: "72",
    metricUnit: "bpm",
    date: "Oct 2, 2024 at 6:15:00 PM",
  },
  {
    metricName: "Cholesterol",
    value: "180",
    metricUnit: "mg/dL",
    date: "Sep 26, 2024 at 8:45:00 AM",
  },
  {
    metricName: "Temperature",
    value: "98.6",
    metricUnit: "°F",
    date: "Sep 28, 2024 at 4:20:00 PM",
  },
];

export const keyInsightsMockData = [
  {
    biometricType: "Blood Glucose",
    latestReading: "110 mg/dL",
    keyInsights: "2 Week Moving Avg",
    keyInsightsValue: "105 mg/dL",
  },
  {
    biometricType: "Blood Pressure",
    latestReading: "120/80 mmHg",
    keyInsights: "Difference (Last 2)",
    keyInsightsValue: "+5 mmHg",
  },
  {
    biometricType: "Heartrate",
    latestReading: "72 bpm",
    keyInsights: "2 Week Moving Avg",
    keyInsightsValue: "75 bpm",
  },
  {
    biometricType: "Weight",
    latestReading: "165 lbs",
    keyInsights: "Difference (Last 2)",
    keyInsightsValue: "-2 lbs",
  },
  {
    biometricType: "Oxygen Saturation",
    latestReading: "98%",
    keyInsights: "2 Week Moving Avg",
    keyInsightsValue: "97%",
  },
  {
    biometricType: "Temperature",
    latestReading: "98.6°F",
    keyInsights: "Difference (Last 2)",
    keyInsightsValue: "+0.2°F",
  },
];

export const deafaultAllNotesMockData = [
  {
    id: 1,
    date: "Sep 25, 2024, 10:34 AM",
    takenBy: "Training Careteam28",
    description: "Session Ended",
  },
  {
    id: 2,
    date: "Sep 23, 2024, 1:07 PM",
    takenBy: "Training Careteam8",
    description: "Session Ended",
  },
  {
    id: 3,
    date: "Sep 12, 2024, 2:53 PM",
    takenBy: "Training Careteam1",
    description: "Session Ended",
  },
];

export const readingNotesMockData = [
  {
    id: 1,
    date: "Aug 25, 2024, 10:34 AM",
    takenBy: "Training Careteam28",
    description:
      "Spoke to the patient on call right now at 4:55 am and he is NOT experiencing headaches, blurry vision, palpitations, and mild/moderate abdominal pain. However, after taking his anti high BP meds as needed, the BP has not changed at all. He needs to be looked at at once for a dose adjustment/change of plan. Sent critical alert to physician.",
    biometrics: {
      bloodPressure: "60/120",
    },
  },
  {
    id: 2,
    date: "Jul 23, 2024, 1:07 PM",
    takenBy: "Training Careteam8",
    description:
      "Patient contacted, he had raised blood pressure due to a missed dose today, counseled the patient to take today's medication and will follow up in the next 30 minutes.",
    biometrics: {
      bloodPressure: "60/120",
    },
  },
  {
    id: 3,
    date: "Mar 12, 2024, 2:53 PM",
    takenBy: "Training Careteam1",
    description:
      "Patient contacted, he had raised blood pressure due to a missed dose today, counselled the patient to take his today's medication, and will follow up in next 30 minutes.",
    biometrics: {
      bloodPressure: "60/120",
    },
  },
];

export const timerNotesMockData = [
  {
    id: 1,
    date: "Oct 07, 2024, 2:23 PM",
    takenBy: "Training Careteam28",
    description: "Session Ended",
  },
  {
    id: 2,
    date: "Sep 25, 2024, 4:21 PM",
    takenBy: "Training Careteam8",
    description: "Session Ended",
  },
  {
    id: 3,
    date: "Jan 12, 2024, 2:53 PM",
    takenBy: "Training Careteam1",
    description: "Session Ended",
  },
];

export const generalNotesMockData = [
  {
    id: 1,
    date: "Dec 16, 2023, 5:56 PM",
    takenBy: "Training Careteam28",
    description: "the patient had taken salty food and was advised rest and increase water intake",
  },
  {
    id: 2,
    date: "Sep 23, 2024, 1:07 PM",
    takenBy: "Training Careteam8",
    description:
      "Engagement call with patient, requested daily blood pressure monitoring with the TupeloLife BLOOD PRESSURE cuff for provider trending and improved blood pressure control.",
  },
  {
    id: 3,
    date: "Dec 16, 2022, 6:18 PM",
    takenBy: "Training Careteam1",
    description:
      "Engagement call with patient, requested daily blood pressure monitoring with the TupeloLife BLOOD PRESSURE cuff for provider trending and improved blood pressure control. Action/Intervention: null",
  },
];
export const alertsMockData = [
  {
    date: "2024-10-10 09:15 AM",
    readingType: "Blood Pressure",
    takenBy: "Training Careteam1",
    alertType: "High Reading",
    readingDateTime: "2024-10-10 09:00 AM",
    reading: "145/95 mmHg",
    stage: "Critical",
    description: "Patient was advised to rest and monitor.",
  },
  {
    date: "2024-10-09 04:25 PM",
    readingType: "Heart Rate",
    takenBy: "Training Careteam1",
    alertType: "Low Reading",
    readingDateTime: "2024-10-09 04:10 PM",
    reading: "55 bpm",
    stage: "Moderate",
    description: "Patient was advised to rest and monitor.",
  },
  {
    date: "2024-10-08 11:10 AM",
    readingType: "Glucose",
    takenBy: "Training Careteam1",
    alertType: "High Reading",
    readingDateTime: "2024-10-08 11:00 AM",
    reading: "180 mg/dL",
    stage: "Warning",
    description: "Patient was advised to rest and monitor.",
  },
  {
    date: "2024-10-07 02:45 PM",
    readingType: "Temperature",
    takenBy: "Training Careteam1",
    alertType: "High Reading",
    readingDateTime: "2024-10-07 02:30 PM",
    reading: "101.5°F",
    stage: "Critical",
    description: "Patient was advised to rest and monitor.",
  },
  {
    date: "2024-10-06 08:55 AM",
    readingType: "Oxygen Saturation",
    takenBy: "Training Careteam1",
    alertType: "Low Reading",
    readingDateTime: "2024-10-06 08:45 AM",
    reading: "88%",
    stage: "Critical",
    description: "Patient was advised to rest and monitor.",
  },
];

export const activeDeviceMockData = [
  {
    id: 1,
    deviceType: "TupeloLife Blood Pressure",
    serialNumber: "863859040792744",
    dateAdded: "Oct 24, 2023",
    battery: "100%",
    signal: "19.4%",
    lastTransmission: "Jun 27, 2024 09:49:00 PM",
    lastSeen: "Jun 27, 2024 09:55:54 PM",
    connectivityInfo: "Connectivity Info",
    remove: "Remove",
  },
  {
    id: 2,
    deviceType: "TupeloLife Blood Pressure",
    serialNumber: "863859040792744",
    dateAdded: "Oct 24, 2023",
    battery: "100%",
    signal: "19.4%",
    lastTransmission: "Jun 27, 2024 09:49:00 PM",
    lastSeen: "Jun 27, 2024 09:55:54 PM",
    connectivityInfo: "Connectivity Info",
    remove: "Remove",
  },
];

export const previouslyUsedDevicesMockData = [
  {
    deviceType: "Fitbit Heart Monitor",
    serialNumber: "564839302194122",
    dateAdded: "Mar 15, 2022",
    lastTransmission: "May 03, 2023 10:15:20 AM",
    removedDate: "May 10, 2023",
  },
  {
    deviceType: "Omron Blood Pressure Monitor",
    serialNumber: "384729194837563",
    dateAdded: "Jul 02, 2021",
    lastTransmission: "Sep 15, 2022 02:50:13 PM",
    removedDate: "Sep 20, 2022",
  },
];

export const customVitalAlertsMockData = [
  {
    title: "Heart Rate Alert",
    vitalType: "Heart Rate",
    condition: "> 120 bpm",
  },
  {
    title: "Blood Pressure",
    vitalType: "Blood Pressure",
    condition: "Systolic > 140 mmHg",
  },
  {
    title: "Oxygen Saturation",
    vitalType: "SpO2",
    condition: "< 92%",
  },
];
