export const dashboardRows = [
  {
    id: 1000,
    name: "James Butt",
    country: {
      name: "Algeria",
      code: "dz",
    },
    company: "Benton, John B Jr",
    date: "2015-09-13",
    status: "unqualified",
    verified: true,
    activity: 17,
    representative: {
      name: "Farhan",
      image: "ionibowcher.png",
    },
    balance: 70663,
  },
  {
    id: 1000,
    name: "James Butt",
    country: {
      name: "Algeria",
      code: "dz",
    },
    company: "Benton, John B Jr",
    date: "2015-09-13",
    status: "unqualified",
    verified: true,
    activity: 17,
    representative: {
      name: "Ioni Bowcher",
      image: "ionibowcher.png",
    },
    balance: 70663,
  },
  {
    id: 1000,
    name: "James Butt",
    country: {
      name: "Algeria",
      code: "dz",
    },
    company: "Benton, John B Jr",
    date: "2015-09-13",
    status: "unqualified",
    verified: true,
    activity: 17,
    representative: {
      name: "Ioni Bowcher",
      image: "ionibowcher.png",
    },
    balance: 70663,
  },
  {
    id: 1000,
    name: "James Butt",
    country: {
      name: "Algeria",
      code: "dz",
    },
    company: "Benton, John B Jr",
    date: "2015-09-13",
    status: "unqualified",
    verified: true,
    activity: 17,
    representative: {
      name: "Ioni Bowcher",
      image: "ionibowcher.png",
    },
    balance: 70663,
  },
  {
    id: 1000,
    name: "James Butt",
    country: {
      name: "Algeria",
      code: "dz",
    },
    company: "Benton, John B Jr",
    date: "2015-09-13",
    status: "unqualified",
    verified: true,
    activity: 17,
    representative: {
      name: "Ioni Bowcher",
      image: "ionibowcher.png",
    },
    balance: 70663,
  },
  {
    id: 1000,
    name: "James Butt",
    country: {
      name: "Algeria",
      code: "dz",
    },
    company: "Benton, John B Jr",
    date: "2015-09-13",
    status: "unqualified",
    verified: true,
    activity: 17,
    representative: {
      name: "Ioni Bowcher",
      image: "ionibowcher.png",
    },
    balance: 70663,
  },
  {
    id: 1000,
    name: "James Butt",
    country: {
      name: "Algeria",
      code: "dz",
    },
    company: "Benton, John B Jr",
    date: "2015-09-13",
    status: "unqualified",
    verified: true,
    activity: 17,
    representative: {
      name: "Ioni Bowcher",
      image: "ionibowcher.png",
    },
    balance: 70663,
  },
  {
    id: 1000,
    name: "James Butt",
    country: {
      name: "Algeria",
      code: "dz",
    },
    company: "Benton, John B Jr",
    date: "2015-09-13",
    status: "unqualified",
    verified: true,
    activity: 17,
    representative: {
      name: "Ioni Bowcher",
      image: "ionibowcher.png",
    },
    balance: 70663,
  },
  {
    id: 1000,
    name: "James Butt",
    country: {
      name: "Algeria",
      code: "dz",
    },
    company: "Benton, John B Jr",
    date: "2015-09-13",
    status: "unqualified",
    verified: true,
    activity: 17,
    representative: {
      name: "Ioni Bowcher",
      image: "ionibowcher.png",
    },
    balance: 70663,
  },
  {
    id: 1000,
    name: "James Butt",
    country: {
      name: "Algeria",
      code: "dz",
    },
    company: "Benton, John B Jr",
    date: "2015-09-13",
    status: "unqualified",
    verified: true,
    activity: 17,
    representative: {
      name: "Ioni Bowcher",
      image: "ionibowcher.png",
    },
    balance: 70663,
  },
  {
    id: 1000,
    name: "James Butt",
    country: {
      name: "Algeria",
      code: "dz",
    },
    company: "Benton, John B Jr",
    date: "2015-09-13",
    status: "unqualified",
    verified: true,
    activity: 17,
    representative: {
      name: "Ioni Bowcher",
      image: "ionibowcher.png",
    },
    balance: 70663,
  },
  {
    id: 1000,
    name: "James Butt",
    country: {
      name: "Algeria",
      code: "dz",
    },
    company: "Benton, John B Jr",
    date: "2015-09-13",
    status: "unqualified",
    verified: true,
    activity: 17,
    representative: {
      name: "Ioni Bowcher",
      image: "ionibowcher.png",
    },
    balance: 70663,
  },
];

export const pendingEnrollmentsRows = [
  {
    id: 10002,
    date: "July 22, 2024",
    name: "Thomas Blackwood",
    dob: "10/16/1951",
    practice: "East Valley Family Physicians",
    deviceType: "BP",
    programType: ["RPM, CCM"],
    status: "First Call",
    progress: 75,
    consent: "Yes",
  },
  {
    id: 10003,
    date: "July 22, 2024",
    name: "James Huddleson",
    dob: "06/23/1980",
    practice: "East Valley Family Physicians",
    deviceType: "BP",
    programType: ["RPM, CCM"],
    status: "Second Call",
    progress: 45,
    consent: "Yes",
  },
  {
    id: 10004,
    date: "July 22, 2024",
    name: "Jim Carter",
    dob: "02/26/1980",
    practice: "East Valley Family Physicians",
    deviceType: "BP",
    programType: ["RPM, CCM"],
    status: "First Call",
    progress: 25,
    consent: "Yes",
  },
  {
    id: 10005,
    date: "July 22, 2024",
    name: "Chris Hemsworth",
    dob: "12/03/1987",
    practice: "East Valley Family Physicians",
    deviceType: "BP",
    programType: ["RPM, CCM"],
    status: "First Call",
    progress: 100,
    consent: "No",
  },
];
export const pendingReadingsRows = [
  {
    id: 7158,
    image: "https://randomuser.me/api/portraits/women/75.jpg",
    dob: "NOV 24, 1950",
    name: "Diana Case",
    type: ["RPM", "CCM"],
    medicare: "Medicare",
    practice: "IntraCare Health Center - Fort Worth",
    provider: "Dr Smith",
    date: "Jul 23 2024",
    trackingStatus: "NO_TRACKING",
    shipped: true,
    trackingDescription: "Non Tracking",
    stageClass: "text-red-500",
    statusClass: "bg-green-100 text-green-700",
  },
  {
    id: 7040,
    image: "https://randomuser.me/api/portraits/men/75.jpg",
    dob: "JAN 12, 1984",
    name: "Gabrielle Hanes",
    type: ["RPM", "CCM"],
    medicare: "Medicare",
    practice: "Prime MD Geriatrics",
    provider: "Dr Kevin",
    date: "Dec 23 2023",
    trackingStatus: "TRACKING",
    shipped: false,
    trackingDescription: "Tracking",
    stageClass: "text-red-500",
    statusClass: "bg-green-100 text-green-700",
  },
  {
    id: 7451,
    image: "https://randomuser.me/api/portraits/women/52.jpg",
    dob: "MAY 14, 1975",
    name: "Samantha Walters",
    type: ["CCM"],
    medicare: "Medicare",
    practice: "Downtown Family Care",
    provider: "Dr Williams",
    date: "Sep 15 2023",
    trackingStatus: "TRACKING",
    shipped: true,
    trackingDescription: "Tracking",
    stageClass: "text-blue-500",
    statusClass: "bg-yellow-100 text-yellow-700",
  },
  {
    id: 7530,
    image: "https://randomuser.me/api/portraits/men/65.jpg",
    dob: "OCT 01, 1962",
    name: "Michael Harper",
    type: ["RPM"],
    medicare: "Medicare Advantage",
    practice: "Parkway Healthcare",
    provider: "Dr Allen",
    date: "Aug 17 2024",
    trackingStatus: "NO_TRACKING",
    shipped: false,
    trackingDescription: "Non Tracking",
    stageClass: "text-red-500",
    statusClass: "bg-green-100 text-green-700",
  },
  {
    id: 7673,
    image: "https://randomuser.me/api/portraits/women/31.jpg",
    dob: "FEB 28, 1992",
    name: "Jessica Green",
    type: ["RPM", "CCM"],
    medicare: "Medicare",
    practice: "Cedar Park Health Clinic",
    provider: "Dr Garcia",
    date: "Jul 5 2024",
    trackingStatus: "TRACKING",
    shipped: true,
    trackingDescription: "Tracking",
    stageClass: "text-blue-500",
    statusClass: "bg-blue-100 text-blue-700",
  },
  {
    id: 7123,
    image: "https://randomuser.me/api/portraits/men/15.jpg",
    dob: "MAR 11, 1955",
    name: "Brian Jennings",
    type: ["CCM"],
    medicare: "Medicare",
    practice: "Oak Ridge Medical Center",
    provider: "Dr Johnson",
    date: "Jun 21 2024",
    trackingStatus: "NO_TRACKING",
    shipped: false,
    trackingDescription: "Non Tracking",
    stageClass: "text-red-500",
    statusClass: "bg-red-100 text-red-700",
  },
  {
    id: 7891,
    image: "https://randomuser.me/api/portraits/women/20.jpg",
    dob: "APR 18, 1980",
    name: "Nancy Stephens",
    type: ["RPM"],
    medicare: "Medicare Advantage",
    practice: "Sunshine Health Partners",
    provider: "Dr Adams",
    date: "Oct 9 2023",
    trackingStatus: "TRACKING",
    shipped: true,
    trackingDescription: "Tracking",
    stageClass: "text-blue-500",
    statusClass: "bg-green-100 text-green-700",
  },
  {
    id: 7325,
    image: "https://randomuser.me/api/portraits/men/24.jpg",
    dob: "JUL 22, 1978",
    name: "James Washington",
    type: ["RPM", "CCM"],
    medicare: "Medicare",
    practice: "Pine Grove Medical",
    provider: "Dr Thompson",
    date: "Sep 29 2024",
    trackingStatus: "NO_TRACKING",
    shipped: false,
    trackingDescription: "Non Tracking",
  },
  {
    id: 7152,
    image: "https://randomuser.me/api/portraits/women/34.jpg",
    dob: "DEC 10, 1966",
    name: "Ashley Turner",
    type: ["CCM"],
    medicare: "Medicare Advantage",
    practice: "Northwest Health Group",
    provider: "Dr Parker",
    date: "Nov 30 2023",
    trackingStatus: "TRACKING",
    shipped: true,
    trackingDescription: "Tracking",
    stageClass: "text-blue-500",
    statusClass: "bg-green-100 text-green-700",
  },
  {
    id: 7982,
    image: "https://randomuser.me/api/portraits/men/45.jpg",
    dob: "AUG 5, 1970",
    name: "David Carter",
    type: ["RPM", "CCM"],
    medicare: "Medicare",
    practice: "Southwest Medical Group",
    provider: "Dr Anderson",
    date: "May 13 2024",
    trackingStatus: "NO_TRACKING",
    shipped: false,
    trackingDescription: "Non Tracking",
  },
];
export const readingNotAddressedRows = [
  {
    id: 7158,
    image: "https://randomuser.me/api/portraits/women/75.jpg",
    name: "Diana Case",
    practice: "IntraCare Health Center - Fort Worth",
    date: "Jul 23 2024",
    readingType: "Blood Pressure",
    reading: "147/81",
    stage: "Hypertension Stage 2",
    stageClass: "text-red-500",
    source: "Tupelolife",
    status: true,
  },
  {
    id: 7040,
    image: "https://randomuser.me/api/portraits/men/75.jpg",
    name: "Gabrielle Hanes",
    practice: "Prime MD Geriatrics",
    date: "Jul 23 2024",
    readingType: "Blood Pressure",
    reading: "153/93",
    stage: "Hypertension Stage 2",
    stageClass: "text-red-500",
    source: "Tupelolife",
    status: false,
  },
  {
    id: 9083,
    image: "https://randomuser.me/api/portraits/women/10.jpg",
    name: "Marta Griffin",
    practice: "Parkway Medical Center",
    date: "Jun 15 2024",
    readingType: "Heart Rate",
    reading: "88 bpm",
    stage: "Normal",
    stageClass: "text-green-500",
    source: "Fitbit",
    status: true,
  },
  {
    id: 3457,
    image: "https://randomuser.me/api/portraits/men/20.jpg",
    name: "John Doe",
    practice: "Eastside Health Clinic",
    date: "Sep 5 2024",
    readingType: "Blood Sugar",
    reading: "125 mg/dL",
    stage: "Pre-diabetes",
    stageClass: "text-yellow-500",
    source: "Glucolife",
    status: false,
  },
  {
    id: 5674,
    image: "https://randomuser.me/api/portraits/women/30.jpg",
    name: "Emily Foster",
    practice: "Central Wellness Clinic",
    date: "Aug 12 2024",
    readingType: "Cholesterol",
    reading: "220 mg/dL",
    stage: "Borderline High",
    stageClass: "text-orange-500",
    source: "LabCorp",
    status: true,
  },
  {
    id: 1823,
    image: "https://randomuser.me/api/portraits/men/40.jpg",
    name: "James Taylor",
    practice: "Bay Area Health Center",
    date: "Oct 1 2024",
    readingType: "Blood Pressure",
    reading: "130/85",
    stage: "Pre-hypertension",
    stageClass: "text-yellow-500",
    source: "Omron",
    status: false,
  },
  {
    id: 6245,
    image: "https://randomuser.me/api/portraits/women/50.jpg",
    name: "Sandra Mitchell",
    practice: "Sunrise Family Health",
    date: "May 30 2024",
    readingType: "Heart Rate",
    reading: "102 bpm",
    stage: "Elevated",
    stageClass: "text-red-500",
    source: "Apple Watch",
    status: true,
  },
  {
    id: 8792,
    image: "https://randomuser.me/api/portraits/men/60.jpg",
    name: "Aaron Black",
    practice: "Greenwood Medical Center",
    date: "Apr 20 2024",
    readingType: "Blood Sugar",
    reading: "95 mg/dL",
    stage: "Normal",
    stageClass: "text-green-500",
    source: "Dexcom",
    status: true,
  },
  {
    id: 9321,
    image: "https://randomuser.me/api/portraits/women/70.jpg",
    name: "Jessica Brown",
    practice: "Westside Health Clinic",
    date: "Mar 18 2024",
    readingType: "Cholesterol",
    reading: "190 mg/dL",
    stage: "Desirable",
    stageClass: "text-green-500",
    source: "LabCorp",
    status: false,
  },
  {
    id: 4519,
    image: "https://randomuser.me/api/portraits/men/80.jpg",
    name: "Michael Harris",
    practice: "Downtown Medical Center",
    date: "Jan 10 2024",
    readingType: "Blood Pressure",
    reading: "160/100",
    stage: "Hypertension Stage 2",
    stageClass: "text-red-500",
    source: "Withings",
    status: false,
  },
];

export const mockDevicesData = [
  {
    type: "Blood Pressure Monitor",
    issueDate: "20-12-2222",
    serial: "124qiyeu49792",
    active: true,
  },
  {
    type: "Blood Pressure Monitor",
    issueDate: "20-12-2222",
    serial: "124qiyeu49792",
    active: false,
  },
  {
    type: "Blood Pressure Monitor",
    issueDate: "20-12-2222",
    serial: "124qiyeu49792",
    active: true,
  },
  {
    type: "Blood Pressure Monitor",
    issueDate: "20-12-2222",
    serial: "124qiyeu49792",
    active: true,
  },
  {
    type: "Blood Pressure Monitor",
    issueDate: "20-12-2222",
    serial: "124qiyeu49792",
    active: false,
  },
  {
    type: "Blood Pressure Monitor",
    issueDate: "20-12-2222",
    serial: "124qiyeu49792",
    active: false,
  },
];
export const callLogsData = [
  {
    dateTime: "Sep 30, 2024",
    callFrom: "Patient A",
    callTo: "Provider A",
    phoneNumber: "1234567890",
    startTime: "10:00 AM",
    endTime: "10:30 AM",
    duration: "00:30",
    status: "Completed",
  },
  {
    dateTime: "Oct 01, 2024",
    callFrom: "Patient B",
    callTo: "Dr. Smith",
    phoneNumber: "9876543210",
    startTime: "09:45 AM",
    endTime: "10:00 AM",
    duration: "00:15",
    status: "Missed",
  },
  {
    dateTime: "Oct 02, 2024",
    callFrom: "Patient C",
    callTo: "Dr. Allen",
    phoneNumber: "5554443333",
    startTime: "01:00 PM",
    endTime: "01:20 PM",
    duration: "00:20",
    status: "Completed",
  },
  {
    dateTime: "Oct 03, 2024",
    callFrom: "Patient D",
    callTo: "Provider B",
    phoneNumber: "3332221111",
    startTime: "11:30 AM",
    endTime: "11:50 AM",
    duration: "00:20",
    status: "Completed",
  },
  {
    dateTime: "Oct 04, 2024",
    callFrom: "Patient E",
    callTo: "Dr. Wilson",
    phoneNumber: "4445556666",
    startTime: "02:00 PM",
    endTime: "02:45 PM",
    duration: "00:45",
    status: "Completed",
  },
  {
    dateTime: "Sep 30, 2024",
    callFrom: "Patient A",
    callTo: "Provider A",
    phoneNumber: "1234567890",
    startTime: "10:00 AM",
    endTime: "10:30 AM",
    duration: "00:30",
    status: "Completed",
  },
  {
    dateTime: "Oct 01, 2024",
    callFrom: "Patient B",
    callTo: "Dr. Smith",
    phoneNumber: "9876543210",
    startTime: "09:45 AM",
    endTime: "10:00 AM",
    duration: "00:15",
    status: "Missed",
  },
  {
    dateTime: "Oct 02, 2024",
    callFrom: "Patient C",
    callTo: "Dr. Allen",
    phoneNumber: "5554443333",
    startTime: "01:00 PM",
    endTime: "01:20 PM",
    duration: "00:20",
    status: "Completed",
  },
  {
    dateTime: "Oct 03, 2024",
    callFrom: "Patient D",
    callTo: "Provider B",
    phoneNumber: "3332221111",
    startTime: "11:30 AM",
    endTime: "11:50 AM",
    duration: "00:20",
    status: "Completed",
  },
  {
    dateTime: "Oct 04, 2024",
    callFrom: "Patient E",
    callTo: "Dr. Wilson",
    phoneNumber: "4445556666",
    startTime: "02:00 PM",
    endTime: "02:45 PM",
    duration: "00:45",
    status: "Completed",
  },
];

export const textLogsData = [
  {
    dateTime: "Sep 30, 2024",
    phoneNumber: "1234567890",
    message: "Reminder: Blood Pressure Check",
    readingType: "Blood Pressure",
    messageStatus: "Sent",
    patientName: "Patient A",
    providerName: "Dr. John",
  },
  {
    dateTime: "Oct 01, 2024",
    phoneNumber: "9876543210",
    message: "Medication Reminder",
    readingType: "Heart Rate",
    messageStatus: "Delivered",
    patientName: "Patient B",
    providerName: "Dr. Smith",
  },
  {
    dateTime: "Oct 02, 2024",
    phoneNumber: "5554443333",
    message: "Appointment Reminder",
    readingType: "Cholesterol",
    messageStatus: "Sent",
    patientName: "Patient C",
    providerName: "Dr. Allen",
  },
  {
    dateTime: "Oct 03, 2024",
    phoneNumber: "3332221111",
    message: "Weekly Health Update",
    readingType: "Blood Sugar",
    messageStatus: "Failed",
    patientName: "Patient D",
    providerName: "Dr. Clark",
  },
  {
    dateTime: "Oct 04, 2024",
    phoneNumber: "4445556666",
    message: "Follow-up Reminder",
    readingType: "Weight",
    messageStatus: "Delivered",
    patientName: "Patient E",
    providerName: "Dr. Wilson",
  },
];
export const timerLogsData = [
  {
    dateTime: "Sep 30, 2024",
    takenBy: "Ajmal Shami",
    startTime: "10:00AM",
    endTime: "10:30AM",
    duration: "00:30",
    billable: "Yes",
    billingCategory: "RPM",
    logType: "Timer",
    patientName: "Patient A",
    doctorName: "Dr. John",
  },
  {
    dateTime: "Oct 01, 2024",
    takenBy: "Training Provider 1",
    startTime: "08:00AM",
    endTime: "08:30AM",
    duration: "00:30",
    billable: "No",
    billingCategory: "CCM",
    logType: "Timer",
    patientName: "Patient B",
    doctorName: "Dr. Smith",
  },
  {
    dateTime: "Oct 02, 2024",
    takenBy: "Training Provider 2",
    startTime: "09:00AM",
    endTime: "09:45AM",
    duration: "00:45",
    billable: "Yes",
    billingCategory: "RPM",
    logType: "Timer",
    patientName: "Patient C",
    doctorName: "Dr. Allen",
  },
  {
    dateTime: "Oct 03, 2024",
    takenBy: "Training Provider 3",
    startTime: "10:15AM",
    endTime: "10:45AM",
    duration: "00:30",
    billable: "No",
    billingCategory: "CCM",
    logType: "Timer",
    patientName: "Patient D",
    doctorName: "Dr. Clark",
  },
  {
    dateTime: "Oct 04, 2024",
    takenBy: "Training Provider 4",
    startTime: "11:00AM",
    endTime: "11:30AM",
    duration: "00:30",
    billable: "Yes",
    billingCategory: "RPM",
    logType: "Timer",
    patientName: "Patient E",
    doctorName: "Dr. Wilson",
  },
];
export const biometricsMockData = [
  {
    metricName: "Blood Glucose",
    value: "98",
    metricUnit: "mg/dL",
    date: "Oct 5, 2024 at 8:15:00 AM",
  },
  {
    metricName: "Blood Pressure",
    value: "120/80",
    metricUnit: "mmHg",
    date: "Oct 3, 2024 at 7:45:00 AM",
  },
  {
    metricName: "Weight",
    value: "165",
    metricUnit: "lbs",
    date: "Sep 29, 2024 at 9:30:00 AM",
  },
  {
    metricName: "Oxygen Saturation",
    value: "98",
    metricUnit: "%",
    date: "Oct 4, 2024 at 5:10:00 PM",
  },
  {
    metricName: "Heart Rate",
    value: "72",
    metricUnit: "bpm",
    date: "Oct 2, 2024 at 6:15:00 PM",
  },
  {
    metricName: "Cholesterol",
    value: "180",
    metricUnit: "mg/dL",
    date: "Sep 26, 2024 at 8:45:00 AM",
  },
  {
    metricName: "Temperature",
    value: "98.6",
    metricUnit: "°F",
    date: "Sep 28, 2024 at 4:20:00 PM",
  },
];
export const keyInsightsMockData = [
  {
    biometricType: "Blood Glucose",
    latestReading: "110 mg/dL",
    keyInsights: "2 Week Moving Avg",
    keyInsightsValue: "105 mg/dL",
  },
  {
    biometricType: "Blood Pressure",
    latestReading: "120/80 mmHg",
    keyInsights: "Difference (Last 2)",
    keyInsightsValue: "+5 mmHg",
  },
  {
    biometricType: "Heartrate",
    latestReading: "72 bpm",
    keyInsights: "2 Week Moving Avg",
    keyInsightsValue: "75 bpm",
  },
  {
    biometricType: "Weight",
    latestReading: "165 lbs",
    keyInsights: "Difference (Last 2)",
    keyInsightsValue: "-2 lbs",
  },
  {
    biometricType: "Oxygen Saturation",
    latestReading: "98%",
    keyInsights: "2 Week Moving Avg",
    keyInsightsValue: "97%",
  },
  {
    biometricType: "Temperature",
    latestReading: "98.6°F",
    keyInsights: "Difference (Last 2)",
    keyInsightsValue: "+0.2°F",
  },
];
export const screeningSchema = [
  {
    categoryId: 1,
    category: "Medical Management",
    questions: [
      {
        questionId: 101,
        title: "Is there anything you would like addressed on this call?",
        required: true,
        isInlineCheckbox: false,
        responses: [
          {
            name: "comment",
            type: "string",
            required: true,
            placeholder: "Write something",
          },
        ],
      },
      {
        questionId: 102,
        title:
          "Has there been any changes in the patient's health condition, acute exacerbation, new diagnosis, ER visit, or hospitalization within the past year?",
        required: true,
        isInlineCheckbox: false,
        responses: [
          {
            name: "checkbox",
            type: "checkbox",
            required: true,
            option: ["Yes", "No"],
            allowMultipleSelections: false,
          },
          {
            name: "comment",
            type: "string",
            required: false,
            placeholder: "Comment",
          },
        ],
      },
      {
        questionId: 103,
        title: "When was the patient's last visit with a provider and what was the purpose of the visit?",
        required: true,
        isInlineCheckbox: false,
        responses: [
          {
            name: "comment",
            type: "string",
            required: true,
            placeholder: "Comment",
          },
        ],
      },
      {
        questionId: 104,
        title: "When is the next provider/specialist visit?",
        required: true,
        isInlineCheckbox: false,
        responses: [
          {
            name: "comment",
            type: "string",
            required: true,
            placeholder: "Comment",
          },
        ],
      },
      {
        questionId: 105,
        title: "When was the patient's last fall and what were the details surrounding the fall?",
        required: true,
        isInlineCheckbox: false,
        responses: [
          {
            name: "comment",
            type: "string",
            required: true,
            placeholder: "Comment",
          },
        ],
      },
    ],
  },
  {
    categoryId: 2,
    category: "Medication Adherence",
    questions: [
      {
        questionId: 201,
        title:
          "Does the assisted living facility staff bring medications to the patient or does someone else help the patient with this?",
        required: true,
        isInlineCheckbox: false,
        responses: [
          {
            name: "comment",
            type: "string",
            required: true,
            placeholder: "Comment",
          },
        ],
      },
      {
        questionId: 202,
        title:
          "Is there anything keeping the patient from taking medications as prescribed by the doctor? (Financial, forgetfulness, etc.)",
        required: true,
        isInlineCheckbox: false,
        responses: [
          {
            name: "checkbox",
            type: "checkbox",
            required: true,
            option: ["Yes", "No"],
            allowMultipleSelections: false,
          },
          {
            name: "comment",
            type: "string",
            required: false,
            placeholder: "Comment",
          },
        ],
      },
      {
        questionId: 203,
        title: "Does the patient know what they are taking their medications for?",
        required: true,
        isInlineCheckbox: false,
        responses: [
          {
            name: "checkbox",
            type: "checkbox",
            required: true,
            option: ["Yes", "No"],
            allowMultipleSelections: false,
          },
          {
            name: "comment",
            type: "string",
            required: false,
            placeholder: "Comment",
          },
        ],
      },
      {
        questionId: 204,
        title: "Are there any other concerns related to medications you would like to be addressed?",
        required: true,
        isInlineCheckbox: false,
        responses: [
          {
            name: "checkbox",
            type: "checkbox",
            required: true,
            option: ["Yes", "No"],
            allowMultipleSelections: false,
          },
          {
            name: "comment",
            type: "string",
            required: false,
            placeholder: "Comment",
          },
        ],
      },
    ],
  },
  {
    categoryId: 3,
    category: "Condition Management",
    questions: [
      {
        questionId: 301,
        title: "What type of support does the patient require to manage their health/mental health conditions?",
        required: true,
        isInlineCheckbox: false,
        responses: [
          {
            name: "comment",
            type: "string",
            required: true,
            placeholder: "Comment",
          },
        ],
      },
      {
        questionId: 302,
        title:
          "What are the patient's current services (HH, PT, sitter, etc.) and has there been a change in required services?",
        required: true,
        isInlineCheckbox: false,
        responses: [
          {
            name: "checkbox",
            type: "checkbox",
            required: true,
            option: ["Yes", "No"],
            allowMultipleSelections: false,
          },
          {
            name: "comment",
            type: "string",
            required: false,
            placeholder: "Comment",
          },
        ],
      },
      {
        questionId: 303,
        title: "How often is the patient's (BP, BS, O2 Sat, Weight) monitored?",
        required: true,
        isInlineCheckbox: false,
        responses: [
          {
            name: "text_input",
            type: "string",
            required: true,
            placeholder: "BP, BS, O2 Sat, Weight",
          },
          {
            name: "radio",
            type: "radio",
            required: true,
            option: ["Daily", "Weekly", "Occasionally"],
            allowMultipleSelections: false,
          },
          {
            name: "comment",
            type: "string",
            required: false,
            placeholder: "Comment",
          },
        ],
      },
    ],
  },
  {
    categoryId: 4,
    category: "Psychosocial",
    questions: [
      {
        questionId: 401,
        title: "What prompted the patient to move into assisted living?",
        required: true,
        isInlineCheckbox: false,
        responses: [
          {
            name: "comment",
            type: "string",
            required: true,
            placeholder: "Comment",
          },
        ],
      },
      {
        questionId: 402,
        title:
          "Does the patient have long term care insurance or the financial ability to receive appropriate services for the duration of life?",
        required: true,
        isInlineCheckbox: false,
        responses: [
          {
            name: "comment",
            type: "string",
            required: true,
            placeholder: "Comment",
          },
        ],
      },
      {
        questionId: 403,
        title: "Does the patient have advanced directives in place and is there a designated POA?",
        required: true,
        isInlineCheckbox: false,
        responses: [
          {
            name: "comment",
            type: "string",
            required: true,
            placeholder: "Comment",
          },
        ],
      },
      {
        questionId: 404,
        title:
          "What does the patient do independently and/or with assistance (bathe, feed, dress, etc.)? Independently",
        required: true,
        isInlineCheckbox: false,
        responses: [
          {
            name: "independently",
            type: "string",
            required: true,
            placeholder: "Independently",
          },
          {
            name: "with_assistance",
            type: "string",
            required: true,
            placeholder: "With assistance",
          },
        ],
      },
    ],
  },
  {
    categoryId: 5,
    category: "Health Literacy",
    questions: [
      {
        questionId: 501,
        title: "Who schedules provider appointments for the patient?",
        required: true,
        isInlineCheckbox: false,
        responses: [
          {
            name: "comment",
            type: "string",
            required: true,
            placeholder: "Comment",
          },
        ],
      },
    ],
  },
];
export const screeningTableMockData = [
  {
    type: "Physical Exam",
    takenBy: "Dr. John Doe",
    date: "2023-09-15",
    time: "09:30",
  },
  {
    type: "Blood Test",
    takenBy: "Nurse Jane Smith",
    date: "2023-09-16",
    time: "14:00",
  },
  {
    type: "X-ray",
    takenBy: "Technician Mike Johnson",
    date: "2023-09-17",
    time: "11:00",
  },
  {
    type: "Consultation",
    takenBy: "Dr. Alice Williams",
    date: "2023-09-18",
    time: "16:30",
  },
  {
    type: "MRI",
    takenBy: "Technician Sarah Lee",
    date: "2023-09-19",
    time: "10:15",
  },
];
export const carePlanMockData = [
  {
    startDate: "2023-07-10",
    diagnosis: "Hypertension",
    goal: "Lower blood pressure",
    reviewDate: "2023-10-10",
    goalCompleted: "No",
  },
  {
    startDate: "2023-05-15",
    diagnosis: "Diabetes Type 2",
    goal: "Maintain stable glucose levels",
    reviewDate: "2023-09-15",
    goalCompleted: "Yes",
  },
  {
    startDate: "2023-03-01",
    diagnosis: "Chronic Pain",
    goal: "Reduce pain levels",
    reviewDate: "2023-08-01",
    goalCompleted: "In Progress",
  },
  {
    startDate: "2023-06-20",
    diagnosis: "Obesity",
    goal: "Lose 10% body weight",
    reviewDate: "2023-12-20",
    goalCompleted: "No",
  },
  {
    startDate: "2023-02-05",
    diagnosis: "Asthma",
    goal: "Improve lung function",
    reviewDate: "2023-09-05",
    goalCompleted: "Yes",
  },
];
export const careplanSchema = [
  {
    categoryId: 1,
    category: "General",
    questions: [
      {
        questionId: 101,
        title: "Patient Goal",
        type: "checkbox",
        isInlineCheckbox: true,
        required: false,
        responses: [
          {
            name: "comment",
            type: "string",
            required: true,
            placeholder: "Write something",
          },
        ],
      },
      {
        questionId: 102,
        title: "Custom Goal",
        type: "checkbox",
        isInlineCheckbox: true,
        required: false,
        responses: [
          {
            name: "comment",
            type: "string",
            required: true,
            placeholder: "Write something",
          },
        ],
      },
      {
        questionId: 103,
        title:
          "Patient will have an emergency plan in place, understands the importance of early intervention, and how to contact PCP.",
        type: "checkbox",
        isInlineCheckbox: true,
        required: false,
        responses: [
          {
            name: "comment",
            type: "string",
            required: true,
            placeholder: "Write something",
          },
        ],
      },
      {
        questionId: 104,
        title:
          "Advance Care Planning: Discuss advance care planning with patients, including living wills, healthcare proxies, and end-of-life care preferences.",
        type: "checkbox",
        isInlineCheckbox: true,
        required: false,
        responses: [
          {
            name: "comment",
            type: "string",
            required: true,
            placeholder: "Write something",
          },
        ],
      },
      {
        questionId: 105,
        title:
          "Caregivers Support: Provide support and resources for caregivers, helping them manage the demands of caring for a loved one.",
        type: "checkbox",
        isInlineCheckbox: true,
        required: false,
        responses: [
          {
            name: "comment",
            type: "string",
            required: true,
            placeholder: "Write something",
          },
        ],
      },
      {
        questionId: 106,
        title:
          "Chronic Disease Self-Management: Educate patients on managing their chronic conditions through lifestyle changes.",
        type: "checkbox",
        isInlineCheckbox: true,
        required: false,
        responses: [
          {
            name: "comment",
            type: "string",
            required: true,
            placeholder: "Write something",
          },
        ],
      },
      {
        questionId: 107,
        title:
          "Coordination of Care: Ensure coordinated care across different healthcare providers to avoid gaps or overlaps in treatment.",
        type: "checkbox",
        isInlineCheckbox: true,
        required: false,
        responses: [
          {
            name: "comment",
            type: "string",
            required: true,
            placeholder: "Write something",
          },
        ],
      },
    ],
  },
  {
    categoryId: 2,
    category: "Nutrition",
    questions: [
      {
        questionId: 201,
        title: "Dietary Assessment: Does the patient have any dietary restrictions?",
        type: "checkbox",
        isInlineCheckbox: true,
        required: false,
        responses: [
          {
            name: "comment",
            type: "string",
            required: true,
            placeholder: "Write dietary restrictions",
          },
        ],
      },
      {
        questionId: 202,
        title: "Nutrition Goals: Set nutrition goals for the patient based on their current health.",
        type: "checkbox",
        isInlineCheckbox: true,
        required: false,
        responses: [
          {
            name: "comment",
            type: "string",
            required: true,
            placeholder: "Write nutrition goals",
          },
        ],
      },
      {
        questionId: 203,
        title: "Consultation: Recommend consultation with a nutritionist or dietitian.",
        type: "checkbox",
        isInlineCheckbox: true,
        required: false,
        responses: [
          {
            name: "comment",
            type: "string",
            required: true,
            placeholder: "Write something",
          },
        ],
      },
    ],
  },
  {
    categoryId: 3,
    category: "Exercise",
    questions: [
      {
        questionId: 301,
        title: "Exercise Plan: Does the patient have a regular exercise routine?",
        type: "checkbox",
        isInlineCheckbox: true,
        required: false,
        responses: [
          {
            name: "comment",
            type: "string",
            required: true,
            placeholder: "Write exercise routine details",
          },
        ],
      },
      {
        questionId: 302,
        title: "Exercise Goals: Set specific exercise goals for the patient.",
        type: "checkbox",
        isInlineCheckbox: true,
        required: false,
        responses: [
          {
            name: "comment",
            type: "string",
            required: true,
            placeholder: "Write exercise goals",
          },
        ],
      },
      {
        questionId: 303,
        title: "Exercise Barriers: Identify any barriers preventing the patient from engaging in physical activity.",
        type: "checkbox",
        isInlineCheckbox: true,
        required: false,
        responses: [
          {
            name: "comment",
            type: "string",
            required: true,
            placeholder: "Write barriers to exercise",
          },
        ],
      },
    ],
  },
  {
    categoryId: 4,
    category: "Mental Health",
    questions: [
      {
        questionId: 401,
        title: "Mental Health Status: Assess the patient’s current mental health status.",
        type: "checkbox",
        isInlineCheckbox: true,
        required: false,
        responses: [
          {
            name: "comment",
            type: "string",
            required: true,
            placeholder: "Write mental health status",
          },
        ],
      },
      {
        questionId: 402,
        title: "Counseling Services: Recommend counseling or therapy services.",
        type: "checkbox",
        isInlineCheckbox: true,
        required: false,
        responses: [
          {
            name: "comment",
            type: "string",
            required: true,
            placeholder: "Write therapy recommendation",
          },
        ],
      },
      {
        questionId: 403,
        title: "Mental Health Goals: Set mental health improvement goals for the patient.",
        type: "checkbox",
        isInlineCheckbox: true,
        required: false,
        responses: [
          {
            name: "comment",
            type: "string",
            required: true,
            placeholder: "Write mental health goals",
          },
        ],
      },
    ],
  },
  {
    categoryId: 5,
    category: "Medication Adherence",
    questions: [
      {
        questionId: 501,
        title: "Medication Review: Review the patient's current medications for effectiveness and adherence.",
        type: "checkbox",
        isInlineCheckbox: true,
        required: false,
        responses: [
          {
            name: "comment",
            type: "string",
            required: true,
            placeholder: "Write medication review",
          },
        ],
      },
      {
        questionId: 502,
        title: "Medication Adherence: Does the patient regularly take their prescribed medications?",
        type: "checkbox",
        isInlineCheckbox: true,
        required: false,
        responses: [
          {
            name: "comment",
            type: "string",
            required: true,
            placeholder: "Write adherence details",
          },
        ],
      },
      {
        questionId: 503,
        title: "Side Effects: Assess any side effects from the current medication regimen.",
        type: "checkbox",
        isInlineCheckbox: true,
        required: false,
        responses: [
          {
            name: "comment",
            type: "string",
            required: true,
            placeholder: "Write side effects details",
          },
        ],
      },
    ],
  },
];
