export const dashboardRows = [
  {
    id: 1000,
    name: "James Butt",
    country: {
      name: "Algeria",
      code: "dz",
    },
    company: "Benton, John B Jr",
    date: "2015-09-13",
    status: "unqualified",
    verified: true,
    activity: 17,
    representative: {
      name: "Farhan",
      image: "ionibowcher.png",
    },
    balance: 70663,
  },
  {
    id: 1000,
    name: "James Butt",
    country: {
      name: "Algeria",
      code: "dz",
    },
    company: "Benton, John B Jr",
    date: "2015-09-13",
    status: "unqualified",
    verified: true,
    activity: 17,
    representative: {
      name: "Ioni Bowcher",
      image: "ionibowcher.png",
    },
    balance: 70663,
  },
  {
    id: 1000,
    name: "James Butt",
    country: {
      name: "Algeria",
      code: "dz",
    },
    company: "Benton, John B Jr",
    date: "2015-09-13",
    status: "unqualified",
    verified: true,
    activity: 17,
    representative: {
      name: "Ioni Bowcher",
      image: "ionibowcher.png",
    },
    balance: 70663,
  },
  {
    id: 1000,
    name: "James Butt",
    country: {
      name: "Algeria",
      code: "dz",
    },
    company: "Benton, John B Jr",
    date: "2015-09-13",
    status: "unqualified",
    verified: true,
    activity: 17,
    representative: {
      name: "Ioni Bowcher",
      image: "ionibowcher.png",
    },
    balance: 70663,
  },
  {
    id: 1000,
    name: "James Butt",
    country: {
      name: "Algeria",
      code: "dz",
    },
    company: "Benton, John B Jr",
    date: "2015-09-13",
    status: "unqualified",
    verified: true,
    activity: 17,
    representative: {
      name: "Ioni Bowcher",
      image: "ionibowcher.png",
    },
    balance: 70663,
  },
  {
    id: 1000,
    name: "James Butt",
    country: {
      name: "Algeria",
      code: "dz",
    },
    company: "Benton, John B Jr",
    date: "2015-09-13",
    status: "unqualified",
    verified: true,
    activity: 17,
    representative: {
      name: "Ioni Bowcher",
      image: "ionibowcher.png",
    },
    balance: 70663,
  },
  {
    id: 1000,
    name: "James Butt",
    country: {
      name: "Algeria",
      code: "dz",
    },
    company: "Benton, John B Jr",
    date: "2015-09-13",
    status: "unqualified",
    verified: true,
    activity: 17,
    representative: {
      name: "Ioni Bowcher",
      image: "ionibowcher.png",
    },
    balance: 70663,
  },
  {
    id: 1000,
    name: "James Butt",
    country: {
      name: "Algeria",
      code: "dz",
    },
    company: "Benton, John B Jr",
    date: "2015-09-13",
    status: "unqualified",
    verified: true,
    activity: 17,
    representative: {
      name: "Ioni Bowcher",
      image: "ionibowcher.png",
    },
    balance: 70663,
  },
  {
    id: 1000,
    name: "James Butt",
    country: {
      name: "Algeria",
      code: "dz",
    },
    company: "Benton, John B Jr",
    date: "2015-09-13",
    status: "unqualified",
    verified: true,
    activity: 17,
    representative: {
      name: "Ioni Bowcher",
      image: "ionibowcher.png",
    },
    balance: 70663,
  },
  {
    id: 1000,
    name: "James Butt",
    country: {
      name: "Algeria",
      code: "dz",
    },
    company: "Benton, John B Jr",
    date: "2015-09-13",
    status: "unqualified",
    verified: true,
    activity: 17,
    representative: {
      name: "Ioni Bowcher",
      image: "ionibowcher.png",
    },
    balance: 70663,
  },
  {
    id: 1000,
    name: "James Butt",
    country: {
      name: "Algeria",
      code: "dz",
    },
    company: "Benton, John B Jr",
    date: "2015-09-13",
    status: "unqualified",
    verified: true,
    activity: 17,
    representative: {
      name: "Ioni Bowcher",
      image: "ionibowcher.png",
    },
    balance: 70663,
  },
  {
    id: 1000,
    name: "James Butt",
    country: {
      name: "Algeria",
      code: "dz",
    },
    company: "Benton, John B Jr",
    date: "2015-09-13",
    status: "unqualified",
    verified: true,
    activity: 17,
    representative: {
      name: "Ioni Bowcher",
      image: "ionibowcher.png",
    },
    balance: 70663,
  },
];

export const pendingEnrollmentsRows = [
  {
    id:10002,
    date: "July 22, 2024",
    name: "Thomas Blackwood",
    dob: "10/16/1951",
    practice: "East Valley Family Physicians",
    deviceType: "BP",
    programType: ["RPM, CCM"],
    status: "First Call",
    progress: 75,
    consent: "Yes",
  },
  {
    id:10003,
    date: "July 22, 2024",
    name: "James Huddleson",
    dob: "06/23/1980",
    practice: "East Valley Family Physicians",
    deviceType: "BP",
    programType: ["RPM, CCM"],
    status: "Second Call",
    progress: 45,
    consent: "Yes",
  },
  {
    id:10004,
    date: "July 22, 2024",
    name: "Jim Carter",
    dob: "02/26/1980",
    practice: "East Valley Family Physicians",
    deviceType: "BP",
    programType: ["RPM, CCM"],
    status: "First Call",
    progress: 25,
    consent: "Yes",
  },
  {
    id:10005,
    date: "July 22, 2024",
    name: "Chris Hemsworth",
    dob: "12/03/1987",
    practice: "East Valley Family Physicians",
    deviceType: "BP",
    programType: ["RPM, CCM"],
    status: "First Call",
    progress: 100,
    consent: "No",
  },
];
export const pendingReadingsRows = [
  {
    id: 7158,
    image: "https://randomuser.me/api/portraits/women/75.jpg",
    dob: "NOV 24, 1950",
    name: "Diana Case",
    type: ["RPM", "CCM"],
    medicare: "Medicare",
    practice: "IntraCare Health Center - Fort Worth",
    provider: "Dr Smith",
    date: "Jul 23 2024",
    trackingStatus: "NO_TRACKING",
    shipped: true,
    trackingDescription: "Non Tracking",
    stageClass: "text-red-500",
    statusClass: "bg-green-100 text-green-700",
  },
  {
    id: 7040,
    image: "https://randomuser.me/api/portraits/men/75.jpg",
    dob: "JAN 12, 1984",
    name: "Gabrielle Hanes",
    type: ["RPM", "CCM"],
    medicare: "Medicare",
    practice: "Prime MD Geriatrics",
    provider: "Dr Kevin",
    date: "Dec 23 2023",
    trackingStatus: "TRACKING",
    shipped: false,
    trackingDescription: "Tracking",
    stageClass: "text-red-500",
    statusClass: "bg-green-100 text-green-700",
  },
  {
    id: 7451,
    image: "https://randomuser.me/api/portraits/women/52.jpg",
    dob: "MAY 14, 1975",
    name: "Samantha Walters",
    type: ["CCM"],
    medicare: "Medicare",
    practice: "Downtown Family Care",
    provider: "Dr Williams",
    date: "Sep 15 2023",
    trackingStatus: "TRACKING",
    shipped: true,
    trackingDescription: "Tracking",
    stageClass: "text-blue-500",
    statusClass: "bg-yellow-100 text-yellow-700",
  },
  {
    id: 7530,
    image: "https://randomuser.me/api/portraits/men/65.jpg",
    dob: "OCT 01, 1962",
    name: "Michael Harper",
    type: ["RPM"],
    medicare: "Medicare Advantage",
    practice: "Parkway Healthcare",
    provider: "Dr Allen",
    date: "Aug 17 2024",
    trackingStatus: "NO_TRACKING",
    shipped: false,
    trackingDescription: "Non Tracking",
    stageClass: "text-red-500",
    statusClass: "bg-green-100 text-green-700",
  },
  {
    id: 7673,
    image: "https://randomuser.me/api/portraits/women/31.jpg",
    dob: "FEB 28, 1992",
    name: "Jessica Green",
    type: ["RPM", "CCM"],
    medicare: "Medicare",
    practice: "Cedar Park Health Clinic",
    provider: "Dr Garcia",
    date: "Jul 5 2024",
    trackingStatus: "TRACKING",
    shipped: true,
    trackingDescription: "Tracking",
    stageClass: "text-blue-500",
    statusClass: "bg-blue-100 text-blue-700",
  },
  {
    id: 7123,
    image: "https://randomuser.me/api/portraits/men/15.jpg",
    dob: "MAR 11, 1955",
    name: "Brian Jennings",
    type: ["CCM"],
    medicare: "Medicare",
    practice: "Oak Ridge Medical Center",
    provider: "Dr Johnson",
    date: "Jun 21 2024",
    trackingStatus: "NO_TRACKING",
    shipped: false,
    trackingDescription: "Non Tracking",
    stageClass: "text-red-500",
    statusClass: "bg-red-100 text-red-700",
  },
  {
    id: 7891,
    image: "https://randomuser.me/api/portraits/women/20.jpg",
    dob: "APR 18, 1980",
    name: "Nancy Stephens",
    type: ["RPM"],
    medicare: "Medicare Advantage",
    practice: "Sunshine Health Partners",
    provider: "Dr Adams",
    date: "Oct 9 2023",
    trackingStatus: "TRACKING",
    shipped: true,
    trackingDescription: "Tracking",
    stageClass: "text-blue-500",
    statusClass: "bg-green-100 text-green-700",
  },
  {
    id: 7325,
    image: "https://randomuser.me/api/portraits/men/24.jpg",
    dob: "JUL 22, 1978",
    name: "James Washington",
    type: ["RPM", "CCM"],
    medicare: "Medicare",
    practice: "Pine Grove Medical",
    provider: "Dr Thompson",
    date: "Sep 29 2024",
    trackingStatus: "NO_TRACKING",
    shipped: false,
    trackingDescription: "Non Tracking",
  },
  {
    id: 7152,
    image: "https://randomuser.me/api/portraits/women/34.jpg",
    dob: "DEC 10, 1966",
    name: "Ashley Turner",
    type: ["CCM"],
    medicare: "Medicare Advantage",
    practice: "Northwest Health Group",
    provider: "Dr Parker",
    date: "Nov 30 2023",
    trackingStatus: "TRACKING",
    shipped: true,
    trackingDescription: "Tracking",
    stageClass: "text-blue-500",
    statusClass: "bg-green-100 text-green-700",
  },
  {
    id: 7982,
    image: "https://randomuser.me/api/portraits/men/45.jpg",
    dob: "AUG 5, 1970",
    name: "David Carter",
    type: ["RPM", "CCM"],
    medicare: "Medicare",
    practice: "Southwest Medical Group",
    provider: "Dr Anderson",
    date: "May 13 2024",
    trackingStatus: "NO_TRACKING",
    shipped: false,
    trackingDescription: "Non Tracking",
  },
];
export const readingNotAddressedRows = [
  {
    id: 7158,
    image: "https://randomuser.me/api/portraits/women/75.jpg",
    name: "Diana Case",
    practice: "IntraCare Health Center - Fort Worth",
    date: "Jul 23 2024",
    readingType: "Blood Pressure",
    reading: "147/81",
    stage: "Hypertension Stage 2",
    stageClass: "text-red-500",
    source: "Tupelolife",
    status: true,
  },
  {
    id: 7040,
    image: "https://randomuser.me/api/portraits/men/75.jpg",
    name: "Gabrielle Hanes",
    practice: "Prime MD Geriatrics",
    date: "Jul 23 2024",
    readingType: "Blood Pressure",
    reading: "153/93",
    stage: "Hypertension Stage 2",
    stageClass: "text-red-500",
    source: "Tupelolife",
    status: false,
  },
  {
    id: 9083,
    image: "https://randomuser.me/api/portraits/women/10.jpg",
    name: "Marta Griffin",
    practice: "Parkway Medical Center",
    date: "Jun 15 2024",
    readingType: "Heart Rate",
    reading: "88 bpm",
    stage: "Normal",
    stageClass: "text-green-500",
    source: "Fitbit",
    status: true,
  },
  {
    id: 3457,
    image: "https://randomuser.me/api/portraits/men/20.jpg",
    name: "John Doe",
    practice: "Eastside Health Clinic",
    date: "Sep 5 2024",
    readingType: "Blood Sugar",
    reading: "125 mg/dL",
    stage: "Pre-diabetes",
    stageClass: "text-yellow-500",
    source: "Glucolife",
    status: false,
  },
  {
    id: 5674,
    image: "https://randomuser.me/api/portraits/women/30.jpg",
    name: "Emily Foster",
    practice: "Central Wellness Clinic",
    date: "Aug 12 2024",
    readingType: "Cholesterol",
    reading: "220 mg/dL",
    stage: "Borderline High",
    stageClass: "text-orange-500",
    source: "LabCorp",
    status: true,
  },
  {
    id: 1823,
    image: "https://randomuser.me/api/portraits/men/40.jpg",
    name: "James Taylor",
    practice: "Bay Area Health Center",
    date: "Oct 1 2024",
    readingType: "Blood Pressure",
    reading: "130/85",
    stage: "Pre-hypertension",
    stageClass: "text-yellow-500",
    source: "Omron",
    status: false,
  },
  {
    id: 6245,
    image: "https://randomuser.me/api/portraits/women/50.jpg",
    name: "Sandra Mitchell",
    practice: "Sunrise Family Health",
    date: "May 30 2024",
    readingType: "Heart Rate",
    reading: "102 bpm",
    stage: "Elevated",
    stageClass: "text-red-500",
    source: "Apple Watch",
    status: true,
  },
  {
    id: 8792,
    image: "https://randomuser.me/api/portraits/men/60.jpg",
    name: "Aaron Black",
    practice: "Greenwood Medical Center",
    date: "Apr 20 2024",
    readingType: "Blood Sugar",
    reading: "95 mg/dL",
    stage: "Normal",
    stageClass: "text-green-500",
    source: "Dexcom",
    status: true,
  },
  {
    id: 9321,
    image: "https://randomuser.me/api/portraits/women/70.jpg",
    name: "Jessica Brown",
    practice: "Westside Health Clinic",
    date: "Mar 18 2024",
    readingType: "Cholesterol",
    reading: "190 mg/dL",
    stage: "Desirable",
    stageClass: "text-green-500",
    source: "LabCorp",
    status: false,
  },
  {
    id: 4519,
    image: "https://randomuser.me/api/portraits/men/80.jpg",
    name: "Michael Harris",
    practice: "Downtown Medical Center",
    date: "Jan 10 2024",
    readingType: "Blood Pressure",
    reading: "160/100",
    stage: "Hypertension Stage 2",
    stageClass: "text-red-500",
    source: "Withings",
    status: false,
  },
];

export const mockDevicesData = [
  {
    type: "Blood Pressure Monitor",
    issueDate: "20-12-2222",
    serial: "124qiyeu49792",
    active: true,
  },
  {
    type: "Blood Pressure Monitor",
    issueDate: "20-12-2222",
    serial: "124qiyeu49792",
    active: false,
  },
  {
    type: "Blood Pressure Monitor",
    issueDate: "20-12-2222",
    serial: "124qiyeu49792",
    active: true,
  },
  {
    type: "Blood Pressure Monitor",
    issueDate: "20-12-2222",
    serial: "124qiyeu49792",
    active: true,
  },
  {
    type: "Blood Pressure Monitor",
    issueDate: "20-12-2222",
    serial: "124qiyeu49792",
    active: false,
  },
  {
    type: "Blood Pressure Monitor",
    issueDate: "20-12-2222",
    serial: "124qiyeu49792",
    active: false,
  },
];
